
$font = Inter

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 3
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = 0.1
    vignette_darkness = 0.5
}

label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1)
    font_size = 60
    font_family = Inter, Sans
    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %B %e"
    color = rgba(255, 255, 255, 1)
    font_size = 20
    font_family = Inter, Sans
    position = 0, -40
    halign = center
    valign = center
}


shape {
    position = 0, 0
    size= 354, 354
    color = rgb(000000)
    border_size = 0
    rounding = -1
}
shape {
    position = 0, 0
    size= 316, 316
    color = rgba(2E3440FF)
    border_size = 0
    rounding = -1
}

input-field {
    monitor =
    hide_input = true

    size = 320, 320
    outline_thickness = 15

    fade_on_empty = false
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgb(143, 143, 143)

    dots_size = 0.0
    dots_spacing = 0.0

    outer_color = rgba(FF0000FF) rgba(00FF00FF) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(FF0000ee)

    placeholder_text =
    fail_text =

    position = 0, 0
    halign = center
    valign = center
}

