[General]
background=/usr/share/sddm/themes/custom/neon-city-dreams-cyberpunk-skies-om.jpg
blur_radius=64
font=Inter
bg_color=#000000

time_font_size=72
date_font_size=28
time_color=#eeeeee
date_color=#aaaaaa

text_color=#eeeeee
text_font_size=26
focus_bg_color=#555555
divider_color=#555555
error_color=#ff0000

box_width=640
box_bg_color=#222222
box_border_color=#555555
box_border_radius=4

