# Set vi-mode
set-window-option -g mode-keys vi

set -g default-terminal "tmux-256color"

# Set true color
set-option -as terminal-overrides ',*:Tc,Smulx=\E[4::%p1%dm'
set -as terminal-features '*:usstyle,italics,overline,strikethrough'

set -g mouse on
set -g set-clipboard on

# General settings
set-window-option -g aggressive-resize on
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix
unbind-key C-b
set -g prefix C-Space
bind C-Space send-prefix

bind R source-file ${XDG_CONFIG_HOME}/tmux/tmux.conf \; display-message "${XDG_CONFIG_HOME}/tmux/tmux.conf reloaded"

# Switch to last window with C-Space Space
bind Space last-window

# Session management keybinds
bind s choose-tree -s
bind r command-prompt -I "" "run-shell \"tmux rename-window \\\"$(echo '%%' | sed 's/ /-/g')\\\"\""
bind x kill-pane
bind Q kill-window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Prefix vim keys to switch windows
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Vim keybinds in Copy Mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# fzf keybinds
set -g @fzf-url-bind "o"

# tmux thumbs
set -g @thumbs-key "F"
set -g @thumbs-command "echo -n {} | wl-copy"

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "wfxr/tmux-fzf-url"
set -g @plugin "wfxr/tmux-fzf-url"
set -g @plugin "fcsonline/tmux-thumbs"

# Setup for resurrect and continuum
set -g @resurrect-dir "${XDG_STATE_HOME}/tmux/resurrect"
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-strategy-vim "session"
set -g @resurrect-strategy-nvim "session"
set -g @resurrect-restore-hook "source ${HOME}/.zshrc"
set -g @continuum-restore "on"

# Tmux theme
source-file ~/.config/tmux/themes/custom.conf

set -g status-interval 15
set -g status-position bottom
set -g status-justify left
set -g status-style "fg=#{@color_text}"
set -g status-left-length 40
set -g status-left "#[fg=#{@color_primary},bold] #S #[fg=#{@color_text},nobold]"
set -g status-right-length 150
set -g status-right "#[fg=#{@color_text}] %d/%m/%Y #[fg=#{@color_primary},bold]%H:%M "
setw -g window-status-separator ""
setw -g window-status-format "  #[fg=#{@color_secondary},bold]#I:#[fg=#{@color_text},bold]#W  "
setw -g window-status-current-style "fg=#{@color_text}"
setw -g window-status-current-format "#[fg=#{@color_text},bold][ #[fg=#{@color_secondary},bold]#I:#[fg=#{@color_text},bold]#W#[fg=#{@color_text},bold] ]"
set -g pane-border-style "fg=#{@color_inactive}"
set -g pane-active-border-style "fg=#{@color_primary}"
set -g message-style "fg=#{@color_text}"
set -g message-command-style "fg=#{@color_text}"
set -g mode-style "#[fg=#{@color_primay},bold]"
set -g copy-mode-current-match-style "fg=#{@color_match_foreground},bg=#{@color_match_background}"
set -g copy-mode-match-style "fg=#{@color_match_foreground},bg=#{@color_match_background}"

set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins"
run "${XDG_DATA_HOME}/tmux/plugins/tpm/tpm"

