PRIMARY="%{$fg[cyan]%}"
FOREGROUND="%{$fg[white]%}"
SECONDARY="%{$fg[red]%}"
RESET="%{$reset_color%}"

ZSH_THEME_GIT_PROMPT_PREFIX="${FOREGROUND} "
ZSH_THEME_GIT_PROMPT_SUFFIX="${RESET}"
ZSH_THEME_GIT_PROMPT_DIRTY="${SECONDARY}~${FOREGROUND}"
ZSH_THEME_GIT_PROMPT_CLEAN="${FOREGROUND}"

PROMPT='${PRIMARY}%2~${RESET}$(git_prompt_info) » ${RESET}%a'

