[main]
shell=/bin/zsh
term=xterm-256color
font=JetBrainsMono Nerd Font:size=11.5
dpi-aware=yes
initial-window-size-chars=120x24
pad=6x6
resize-keep-grid=no

#include=~/.config/foot/custom.ini

[colors-dark]
alpha=0.85
blur=yes

[bell]
system=no

[scrollback]
lines=10000
multiplier=5

[search-bindings]
find-prev=Control+p
find-next=Control+n

